[package]
name = "rust-factors"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-rt = "2.10.0"
async-trait = "0.1.80"
derivative = "2.2.0"
indexmap = "2.2.6"
itertools = "0.13.0"
once_cell = "1.19.0"
rand = "0.8.5"
thiserror = "1.0.61"
uuid = { version = "1.8.0", features = ["v4"] }
